# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is this answer correct?'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='html',
            field=models.TextField(verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='html',
            field=models.TextField(verbose_name='Question Text'),
        ),
    ]
