# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180218_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Has been published?'),
        ),
    ]
